// <auto-generated />
using System;
using BlazorApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415084729_ChangeId_AddVarinatId")]
    partial class ChangeId_AddVarinatId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp.Models.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateChanged")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OctopusId")
                        .HasColumnType("int");

                    b.Property<string>("PreviousValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("BlazorApp.Models.Product", b =>
                {
                    b.Property<int>("OctopusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OctopusId"));

                    b.Property<double>("Alcohol")
                        .HasColumnType("double");

                    b.Property<int>("Available")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("KegCollar")
                        .HasColumnType("int");

                    b.Property<string>("OctopusTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PdfTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("PricePrUnit")
                        .HasColumnType("double");

                    b.Property<double>("Str")
                        .HasColumnType("double");

                    b.Property<int>("VariantId1")
                        .HasColumnType("int");

                    b.Property<int>("VariantId2")
                        .HasColumnType("int");

                    b.Property<int>("WebId")
                        .HasColumnType("int");

                    b.Property<string>("WebTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("OctopusId");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
