// <auto-generated />
using BlazorApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp.Models.Product", b =>
                {
                    b.Property<string>("OctopusId")
                        .HasColumnType("varchar(255)");

                    b.Property<double>("Alcohol")
                        .HasColumnType("double");

                    b.Property<int>("Available")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("KegCollar")
                        .HasColumnType("int");

                    b.Property<string>("OctopusTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PdfTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("PricePrUnit")
                        .HasColumnType("double");

                    b.Property<double>("Str")
                        .HasColumnType("double");

                    b.Property<string>("WebId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WebTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("OctopusId");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
