// <auto-generated />
using System;
using BlazorApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PriceLabel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BlazorApp.Models.CategoryColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayLabel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryColumns");
                });

            modelBuilder.Entity("BlazorApp.Models.DraftBeer", b =>
                {
                    b.Property<int>("OctopusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OctopusId"));

                    b.Property<double>("Alcohol")
                        .HasColumnType("double");

                    b.Property<int>("Available")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("InUse")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Kobling")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Land")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OctopusTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PdfTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("PricePrUnit")
                        .HasColumnType("double");

                    b.Property<double>("Str")
                        .HasColumnType("double");

                    b.Property<int>("VariantId1")
                        .HasColumnType("int");

                    b.Property<int>("VariantId2")
                        .HasColumnType("int");

                    b.Property<int>("WebId")
                        .HasColumnType("int");

                    b.Property<string>("WebTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("OctopusId");

                    b.ToTable("DraftBeers");
                });

            modelBuilder.Entity("BlazorApp.Models.LogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateChanged")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<int?>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int>("OctopusId")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("BlazorApp.Models.Product", b =>
                {
                    b.Property<int>("OctopusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OctopusId"));

                    b.Property<double>("Alcohol")
                        .HasColumnType("double");

                    b.Property<int>("Available")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("HalfKolli")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("InUse")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("KegCollar")
                        .HasColumnType("int");

                    b.Property<string>("OctopusTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PdfTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("PricePrUnit")
                        .HasColumnType("double");

                    b.Property<double>("Str")
                        .HasColumnType("double");

                    b.Property<int>("VariantId1")
                        .HasColumnType("int");

                    b.Property<int>("VariantId2")
                        .HasColumnType("int");

                    b.Property<int>("WebId")
                        .HasColumnType("int");

                    b.Property<string>("WebTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("OctopusId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BlazorApp.Models.CategoryColumn", b =>
                {
                    b.HasOne("BlazorApp.Models.Category", "Category")
                        .WithMany("Columns")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BlazorApp.Models.Category", b =>
                {
                    b.Navigation("Columns");
                });
#pragma warning restore 612, 618
        }
    }
}
